"""The auth layer: the only barrier once the API leaves 127.0.0.1.

These drive the exported dependency exactly as a route will use it, on a
throwaway app declared here rather than through ``create_app``. The real routes
are guarded too, and ``test_route_auth.py`` locks that down; keeping the
dependency's own behaviour on a two-route app means a failure here says "the
guard is broken" instead of "something in the API changed".

Every test here is a regression lock on something that fails silently: a
rejection body that says too much, a revoked key that keeps working, a secret
that turns out to be recoverable from the row that stored it, a second
implementation of the key table drifting away from the first.
"""

from __future__ import annotations

import logging
import time
from collections.abc import AsyncIterator

import httpx
import pytest
from fastapi import Depends, FastAPI
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession, async_sessionmaker

from cipherchain.api.auth import (
    ApiKeyAuth,
    AuthenticatedKey,
    MintedKey,
    RevokeOutcome,
    Scope,
    hash_secret,
    list_keys,
    mint_key,
    revoke_key,
    verify_secret,
)
from cipherchain.core.config import Settings
from cipherchain.storage.db import create_session_factory
from cipherchain.storage.repositories import ApiKeyRepository

# The api_keys table belongs to the schema migration (schema contract). Created
# here when that migration has not reached the test database yet, so the auth
# tests do not depend on which change lands first; a no-op once it has.
API_KEYS_DDL = """
CREATE TABLE IF NOT EXISTS api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_id TEXT NOT NULL UNIQUE,
    key_hash TEXT NOT NULL,
    scopes TEXT NOT NULL,
    label TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    revoked_at TIMESTAMPTZ
)
"""


@pytest.fixture
async def keys(engine: AsyncEngine) -> AsyncIterator[async_sessionmaker[AsyncSession]]:
    async with engine.begin() as conn:
        await conn.execute(text(API_KEYS_DDL))
        await conn.execute(text("DELETE FROM api_keys"))
    yield create_session_factory(engine)


def build_app(auth: ApiKeyAuth) -> FastAPI:
    """Two routes, two scopes — the shape the real API will use.

    Each route is wired a different way on purpose, because both wirings must
    enforce: ``/read`` takes the caller as a parameter (so a test can prove
    *which* key was resolved, not merely that something got through), while
    ``/investigate`` guards at the decorator and never sees the key.

    Neither uses ``Annotated[..., Depends(auth.requires(...))]``. Under
    ``from __future__ import annotations`` that annotation is a string
    evaluated against module globals, where the local ``auth`` does not exist;
    FastAPI then reads the parameter as a query parameter and the route stops
    being guarded at all. See ApiKeyAuth's docstring.
    """
    app = FastAPI()
    # Bound to a name first: a bare ``Depends(...)`` call in a default argument
    # is what ruff's B008 objects to, and the name reads the same to FastAPI.
    reader = Depends(auth.requires(Scope.READ))

    @app.get("/read")
    async def read(key: AuthenticatedKey = reader) -> dict[str, object]:
        return {"key_id": key.key_id, "scopes": sorted(key.scopes), "label": key.label}

    @app.post("/investigate", dependencies=[Depends(auth.requires(Scope.INVESTIGATE))])
    async def investigate() -> dict[str, object]:
        return {"started": True}

    return app


async def client_for(auth: ApiKeyAuth) -> httpx.AsyncClient:
    transport = httpx.ASGITransport(app=build_app(auth))
    return httpx.AsyncClient(transport=transport, base_url="http://test")


@pytest.fixture
async def client(keys: async_sessionmaker[AsyncSession]) -> AsyncIterator[httpx.AsyncClient]:
    async with await client_for(ApiKeyAuth(keys, enabled=True)) as c:
        yield c


async def mint(
    keys: async_sessionmaker[AsyncSession],
    *scopes: Scope,
    label: str | None = None,
) -> MintedKey:
    async with keys() as session:
        return await mint_key(session, scopes, label=label)


def bearer(token: str) -> dict[str, str]:
    return {"Authorization": f"Bearer {token}"}


# ──────────────────────────────── the happy path ────────────────────────────────


async def test_a_valid_key_reaches_the_route_its_scope_covers(
    client: httpx.AsyncClient, keys: async_sessionmaker[AsyncSession]
) -> None:
    """A minted key authenticates, and the route learns who it is talking to."""
    minted = await mint(keys, Scope.READ, Scope.INVESTIGATE, label="Det. Ruiz")

    response = await client.get("/read", headers=bearer(minted.token))

    assert response.status_code == 200, response.text
    body = response.json()
    assert body["key_id"] == minted.key_id
    assert body["scopes"] == ["investigate", "read"]
    assert body["label"] == "Det. Ruiz"


async def test_two_minted_keys_never_share_an_id_or_a_secret(
    keys: async_sessionmaker[AsyncSession],
) -> None:
    """Both halves are drawn from ``secrets``; a collision in either would let
    one investigator's key answer for another's."""
    first = await mint(keys, Scope.READ)
    second = await mint(keys, Scope.READ)

    assert first.key_id != second.key_id
    assert first.secret != second.secret
    assert first.key_id.startswith("cc_")
    assert first.token == f"{first.key_id}.{first.secret}"


# ──────────────────────────────── the rejections ────────────────────────────────


async def test_an_unknown_key_id_is_rejected(client: httpx.AsyncClient) -> None:
    response = await client.get("/read", headers=bearer("cc_0000000000000000.not-a-secret"))
    assert response.status_code == 401


async def test_the_right_key_id_with_the_wrong_secret_is_rejected(
    client: httpx.AsyncClient, keys: async_sessionmaker[AsyncSession]
) -> None:
    """Knowing a key id — which appears in logs and audit rows — must buy
    nothing on its own."""
    minted = await mint(keys, Scope.READ)

    response = await client.get("/read", headers=bearer(f"{minted.key_id}.wrong"))

    assert response.status_code == 401


async def test_a_revoked_key_stops_working_on_the_very_next_request(
    client: httpx.AsyncClient, keys: async_sessionmaker[AsyncSession]
) -> None:
    """Revocation is the emergency lever, so it fails closed immediately.

    This is the test that forbids a verification cache: any in-process memo of
    a verified secret would keep the key alive past this point.
    """
    minted = await mint(keys, Scope.READ)
    assert (await client.get("/read", headers=bearer(minted.token))).status_code == 200

    async with keys() as session:
        assert await revoke_key(session, minted.key_id) is RevokeOutcome.REVOKED

    assert (await client.get("/read", headers=bearer(minted.token))).status_code == 401


async def test_a_request_with_no_authorization_header_is_rejected(
    client: httpx.AsyncClient,
) -> None:
    response = await client.get("/read")
    assert response.status_code == 401


async def test_a_decorator_guarded_route_also_rejects_an_anonymous_caller(
    client: httpx.AsyncClient,
) -> None:
    """The other wiring form, checked against the bare 401 rather than a scope.

    ``/investigate`` guards at the decorator, which is the form most routes will
    use. Its rejections are otherwise only exercised through the 403 scope path,
    and a 403 proves the dependency ran for a key that was already *verified* —
    it says nothing about a caller presenting nothing at all. Given that the
    wrong wiring of this exact dependency fails open (see ApiKeyAuth), the form
    that never touches the key needs its own anonymous-caller lock.
    """
    response = await client.post("/investigate")

    assert response.status_code == 401
    assert response.json()["detail"] == "invalid or missing API key"
    assert response.headers["WWW-Authenticate"] == "Bearer"


@pytest.mark.parametrize(
    "header",
    [
        "",
        "Bearer",
        "Bearer ",
        "cc_1111111111111111.secret",  # no scheme at all
        "Basic Zm9vOmJhcg==",
        "Bearer cc_1111111111111111",  # no separator, so no secret
        "Bearer .secret",  # no key id
        "Bearer cc_1111111111111111.",  # no secret
        "Token cc_1111111111111111.secret",
    ],
)
async def test_a_malformed_authorization_header_is_rejected(
    client: httpx.AsyncClient, header: str
) -> None:
    """Every way of getting the header wrong lands on the same 401.

    A parser that answered differently per malformation would tell an attacker
    which half of the token it got right.
    """
    response = await client.get("/read", headers={"Authorization": header})
    assert response.status_code == 401
    assert response.json()["detail"] == "invalid or missing API key"


async def test_the_401_tells_the_client_which_scheme_to_use(client: httpx.AsyncClient) -> None:
    """Naming the scheme is about the endpoint, not about the key (RFC 7235)."""
    response = await client.get("/read")
    assert response.headers["WWW-Authenticate"] == "Bearer"


async def test_every_rejection_says_exactly_the_same_thing(
    client: httpx.AsyncClient, keys: async_sessionmaker[AsyncSession]
) -> None:
    """The user-enumeration oracle this layer must never become.

    Unknown key, wrong secret, revoked key and no header at all are four very
    different server states. If the response distinguishes them, an attacker
    can sweep for valid key ids and then only has to guess one secret. They
    return one status and one body, byte for byte.
    """
    revoked = await mint(keys, Scope.READ)
    live = await mint(keys, Scope.READ)
    async with keys() as session:
        await revoke_key(session, revoked.key_id)

    responses = [
        await client.get("/read"),
        await client.get("/read", headers=bearer("cc_dead0000dead0000.whatever")),
        await client.get("/read", headers=bearer(f"{live.key_id}.wrong-secret")),
        await client.get("/read", headers=bearer(revoked.token)),
    ]

    assert {r.status_code for r in responses} == {401}
    assert len({r.text for r in responses}) == 1
    for response in responses:
        assert revoked.key_id not in response.text
        assert live.key_id not in response.text
        assert "revoked" not in response.text.lower()
        assert "unknown" not in response.text.lower()


async def test_an_unknown_key_still_pays_the_key_derivation_cost(
    client: httpx.AsyncClient, keys: async_sessionmaker[AsyncSession]
) -> None:
    """Identical bodies are not enough — the timing must match too.

    Without the decoy digest, "no such key" answers from a single indexed
    SELECT while "wrong secret" answers 54 ms later, which is the same
    enumeration oracle written in latency instead of in JSON.

    The bound is deliberately loose (10 ms against a measured ~54 ms of
    scrypt): it only has to catch the decoy being deleted, and a tight bound
    on a shared machine would flake.
    """
    await mint(keys, Scope.READ)
    await client.get("/read", headers=bearer("cc_0000000000000000.warmup"))  # warm the decoy

    start = time.perf_counter()
    response = await client.get("/read", headers=bearer("cc_1111111111111111.nope"))
    elapsed = time.perf_counter() - start

    assert response.status_code == 401
    assert elapsed > 0.010, "an unknown key id was rejected without running the KDF"


# ──────────────────────────────── scopes ────────────────────────────────


async def test_a_read_only_key_cannot_start_an_investigation(
    client: httpx.AsyncClient, keys: async_sessionmaker[AsyncSession]
) -> None:
    """The whole point of having scopes: reading results is cheap, starting a
    trace spends provider quota and minutes of work. 403, not 401 — the key is
    known, it simply may not do this."""
    minted = await mint(keys, Scope.READ)

    allowed = await client.get("/read", headers=bearer(minted.token))
    refused = await client.post("/investigate", headers=bearer(minted.token))

    assert allowed.status_code == 200
    assert refused.status_code == 403
    assert "investigate" in refused.json()["detail"]


async def test_a_scope_name_the_store_would_split_is_refused_at_mint(
    keys: async_sessionmaker[AsyncSession],
) -> None:
    """One scope string may not become two privileges on the way to the table.

    Scopes are stored space-separated and read back by splitting on spaces and
    commas, so ``"read investigate"`` — one name, as a caller that joined a
    list or read a config value would produce it — was written as one string
    and resolved as BOTH scopes. The key then held ``investigate`` because of
    a whitespace character, and every scope check downstream agreed with it.
    """
    async with keys() as session:
        with pytest.raises(ValueError, match="several scopes"):
            await mint_key(session, ["read investigate"])
        with pytest.raises(ValueError, match="several scopes"):
            await mint_key(session, ["read,investigate"])

    # And the legitimate way to ask for both still works.
    both = await mint(keys, Scope.READ, Scope.INVESTIGATE)
    assert both.scopes == frozenset({"read", "investigate"})


async def test_an_investigate_key_does_not_inherit_read(
    client: httpx.AsyncClient, keys: async_sessionmaker[AsyncSession]
) -> None:
    """Scopes are flat. If INVESTIGATE quietly implied READ, the separation
    above would depend on which scope a route happened to name first."""
    minted = await mint(keys, Scope.INVESTIGATE)

    assert (await client.post("/investigate", headers=bearer(minted.token))).status_code == 200
    assert (await client.get("/read", headers=bearer(minted.token))).status_code == 403


async def test_the_same_dependency_object_is_reused_for_a_scope_set(
    keys: async_sessionmaker[AsyncSession],
) -> None:
    """FastAPI caches a dependency's result per request by callable identity;
    a fresh closure per call would re-run the 54 ms KDF for every declaration
    naming the same scope. Order of the arguments is not part of the identity."""
    auth = ApiKeyAuth(keys)

    assert auth.requires(Scope.READ) is auth.requires(Scope.READ)
    assert auth.requires(Scope.READ) is not auth.requires(Scope.INVESTIGATE)
    assert auth.requires(Scope.READ, Scope.INVESTIGATE) is auth.requires(
        Scope.INVESTIGATE, Scope.READ
    )


# ──────────────────────────────── stored material ────────────────────────────────


async def test_the_secret_cannot_be_recovered_from_what_is_stored(
    client: httpx.AsyncClient, keys: async_sessionmaker[AsyncSession]
) -> None:
    """A stolen database dump must not yield a working key.

    Three claims: the secret appears nowhere in its own row; the stored digest
    is a slow-KDF record rather than a bare hash; and replaying the digest
    itself as the secret does not authenticate.
    """
    minted = await mint(keys, Scope.READ, label="dump target")
    async with keys() as session:
        row = (
            (
                await session.execute(
                    text("SELECT * FROM api_keys WHERE key_id = :k"), {"k": minted.key_id}
                )
            )
            .mappings()
            .one()
        )

    stored = " ".join(str(value) for value in row.values())
    assert minted.secret not in stored
    assert minted.token not in stored

    key_hash = str(row["key_hash"])
    algorithm, n, r, p, salt, digest = key_hash.split("$")
    assert algorithm == "scrypt"
    assert int(n) >= 2**14 and int(r) >= 8 and int(p) >= 1
    assert salt and digest
    # Sanity: this really is the row that verifies the minted secret, so the
    # absence checks above were made against the right bytes.
    assert verify_secret(minted.secret, key_hash) is True

    replay = await client.get("/read", headers=bearer(f"{minted.key_id}.{key_hash}"))
    assert replay.status_code == 401
    replay_digest = await client.get("/read", headers=bearer(f"{minted.key_id}.{digest}"))
    assert replay_digest.status_code == 401


async def test_two_keys_with_the_same_secret_store_different_digests() -> None:
    """Per-key salt: without it, one precomputed table cracks every key at once
    and equal digests would tell an attacker two keys share a secret."""
    first, second = hash_secret("identical"), hash_secret("identical")

    assert first != second
    assert verify_secret("identical", first) and verify_secret("identical", second)
    assert not verify_secret("identical ", first)


async def test_a_digest_record_that_cannot_be_parsed_verifies_false() -> None:
    """Fail closed. A truncated or foreign hash column must reject every
    secret, not fall through to some looser comparison."""
    for record in ["", "sha256$deadbeef", "scrypt$16384$8", "scrypt$x$8$1$aa$bb", "$$$$$"]:
        assert verify_secret("anything", record) is False


async def test_listing_keys_never_returns_credential_material(
    keys: async_sessionmaker[AsyncSession],
) -> None:
    """The admin listing is printed and logged; it must carry nothing that
    could be replayed, including the digest."""
    minted = await mint(keys, Scope.READ, label="listed")
    async with keys() as session:
        listed = await list_keys(session)

    entry = next(k for k in listed if k.key_id == minted.key_id)
    assert entry.scopes == {"read"}
    assert entry.label == "listed"
    assert entry.active is True
    assert not hasattr(entry, "key_hash")
    assert minted.secret not in repr(entry)
    # The secret is kept out of the minted key's repr for the same reason: a
    # traceback or a debug log must not print it.
    assert minted.secret not in repr(minted)


async def test_revoking_reports_what_actually_happened(
    keys: async_sessionmaker[AsyncSession],
) -> None:
    """An operator revoking a mistyped key id must be told, not reassured."""
    minted = await mint(keys, Scope.READ)
    async with keys() as session:
        assert await revoke_key(session, minted.key_id) is RevokeOutcome.REVOKED
        assert await revoke_key(session, minted.key_id) is RevokeOutcome.ALREADY_REVOKED
        assert await revoke_key(session, "cc_9999999999999999") is RevokeOutcome.UNKNOWN

        listed = {k.key_id: k for k in await list_keys(session)}
    # Revoked keys stay listed: an audit needs the dead ones too.
    assert listed[minted.key_id].active is False
    assert listed[minted.key_id].revoked_at is not None


# ──────────────────────────────── one key store ────────────────────────────────


async def test_auth_and_the_repository_are_looking_at_the_same_rows(
    client: httpx.AsyncClient, keys: async_sessionmaker[AsyncSession]
) -> None:
    """There is one implementation of the api_keys table, and this proves it.

    ``api/auth.py`` used to carry its own INSERT/UPDATE/SELECT over these rows
    beside ``ApiKeyRepository``'s. Two implementations of a credential store is
    a security bug with a delay fuse: the day one of them learns something the
    other does not — that a revoked row must never authenticate — the drift IS
    the vulnerability, and both halves still pass their own tests.

    So: a key minted through the auth layer is visible to the repository, and a
    key revoked through the REPOSITORY stops authenticating immediately. Neither
    holds if there are two tables' worth of code again.
    """
    minted = await mint(keys, Scope.READ)

    async with keys() as session:
        stored = await ApiKeyRepository(session).by_key_id(minted.key_id)
    assert stored is not None
    assert verify_secret(minted.secret, stored.key_hash) is True
    assert (await client.get("/read", headers=bearer(minted.token))).status_code == 200

    async with keys() as session:
        assert await ApiKeyRepository(session).revoke(minted.key_id) is True
        await session.commit()

    assert (await client.get("/read", headers=bearer(minted.token))).status_code == 401


# ──────────────────────────────── the config switch ────────────────────────────────


async def test_auth_is_enabled_unless_a_deployment_turns_it_off(
    keys: async_sessionmaker[AsyncSession], monkeypatch: pytest.MonkeyPatch
) -> None:
    """The default has to be ON. Defaulting the other way fails silently — a
    host that forgot the setting would serve case material to the internet and
    nothing would look wrong."""
    monkeypatch.delenv("AUTH_ENABLED", raising=False)
    assert Settings(_env_file=None).auth_enabled is True
    assert ApiKeyAuth.from_settings(keys, Settings(_env_file=None)).enabled is True

    monkeypatch.setenv("AUTH_ENABLED", "false")
    assert Settings(_env_file=None).auth_enabled is False
    assert ApiKeyAuth.from_settings(keys, Settings(_env_file=None)).enabled is False


async def test_disabling_auth_opens_the_routes_and_says_so_loudly(
    keys: async_sessionmaker[AsyncSession], caplog: pytest.LogCaptureFixture
) -> None:
    """Local development stays frictionless, but never quietly.

    The banner is the compensating control: the operator who turned auth off
    for a local run must trip over that fact in the first screen of logs.
    """
    with caplog.at_level(logging.WARNING, logger="cipherchain.api.auth"):
        auth = ApiKeyAuth(keys, enabled=False)

    warnings = " ".join(record.message for record in caplog.records)
    assert "DISABLED" in warnings
    assert "127.0.0.1" in warnings
    assert auth.enabled is False

    async with await client_for(auth) as open_client:
        response = await open_client.get("/read")
    assert response.status_code == 200
    # Named so an audit row reads "auth-disabled" instead of naming a key that
    # was never presented.
    assert response.json()["key_id"] == "auth-disabled"


async def test_enabling_auth_does_not_shout(
    keys: async_sessionmaker[AsyncSession], caplog: pytest.LogCaptureFixture
) -> None:
    """The banner must mean something: it only appears when auth is off."""
    with caplog.at_level(logging.WARNING, logger="cipherchain.api.auth"):
        ApiKeyAuth(keys, enabled=True)
    assert caplog.records == []
