"""core tables

Revision ID: a2dba3c20143
Revises:
Create Date: 2026-08-07 15:24:05.631115
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "a2dba3c20143"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "addresses",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("chain", sa.Text(), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_addresses")),
        sa.UniqueConstraint("chain", "address", name="uq_addresses_identity"),
    )
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("chain", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("contract", sa.Text(), nullable=True),
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("decimals", sa.Integer(), nullable=False),
        sa.CheckConstraint("kind IN ('native','token')", name=op.f("ck_assets_kind_values")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint(
            "chain",
            "kind",
            "contract",
            name="uq_assets_identity",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_table(
        "provider_cache",
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("chain", sa.Text(), nullable=False),
        sa.Column("capability", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("raw", sa.LargeBinary(), nullable=False),
        sa.Column("payload_json", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("cache_key", name=op.f("pk_provider_cache")),
    )
    op.create_index(
        "ix_provider_cache_chain_capability",
        "provider_cache",
        ["chain", "capability"],
        unique=False,
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("chain", sa.Text(), nullable=False),
        sa.Column("tx_hash", sa.Text(), nullable=False),
        sa.Column("block_number", sa.BigInteger(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_sha256", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
        sa.UniqueConstraint("chain", "tx_hash", name="uq_transactions_identity"),
    )
    op.create_table(
        "investigations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("root_address_id", sa.BigInteger(), nullable=False),
        sa.Column("objectives", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("budgets", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("spent", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("engine_version", sa.Text(), nullable=False),
        sa.Column("ruleset_version", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('created','running','paused','completed','partial','failed')",
            name=op.f("ck_investigations_status_values"),
        ),
        sa.ForeignKeyConstraint(
            ["root_address_id"], ["addresses.id"], name=op.f("fk_investigations_root_address_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_investigations")),
    )
    op.create_table(
        "movements",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("transaction_id", sa.BigInteger(), nullable=False),
        sa.Column("from_address_id", sa.BigInteger(), nullable=True),
        sa.Column("to_address_id", sa.BigInteger(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=78, scale=0), nullable=False),
        sa.Column("index_in_tx", sa.Integer(), nullable=False),
        sa.Column("dedup_key", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "kind IN ('native','token','internal','utxo_input','utxo_output')",
            name=op.f("ck_movements_kind_values"),
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_movements_amount_nonnegative")),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], name=op.f("fk_movements_asset_id")),
        sa.ForeignKeyConstraint(
            ["from_address_id"], ["addresses.id"], name=op.f("fk_movements_from_address_id")
        ),
        sa.ForeignKeyConstraint(
            ["to_address_id"], ["addresses.id"], name=op.f("fk_movements_to_address_id")
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"], ["transactions.id"], name=op.f("fk_movements_transaction_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_movements")),
        sa.UniqueConstraint("transaction_id", "dedup_key", name="uq_movements_identity"),
    )
    op.create_index(
        "ix_movements_from_time", "movements", ["from_address_id", "timestamp"], unique=False
    )
    op.create_index(
        "ix_movements_to_time", "movements", ["to_address_id", "timestamp"], unique=False
    )
    op.create_table(
        "findings",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("investigation_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("subject_address_id", sa.BigInteger(), nullable=True),
        sa.Column("direction", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Double(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('vasp_endpoint','sanctioned_address','mixer_interaction','bridge_crossing','sweep_pattern','obfuscation_pattern','terminal')",
            name=op.f("ck_findings_kind_values"),
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
            name=op.f("fk_findings_investigation_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subject_address_id"], ["addresses.id"], name=op.f("fk_findings_subject_address_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
    )
    op.create_table(
        "nodes",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("investigation_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("address_id", sa.BigInteger(), nullable=True),
        sa.Column("transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("direction", sa.Text(), nullable=True),
        sa.Column("hop_distance", sa.Integer(), nullable=False),
        sa.Column("value_share", sa.Numeric(precision=78, scale=0), nullable=True),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("discovered_reason", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'address' AND address_id IS NOT NULL AND transaction_id IS NULL) OR (kind = 'transaction' AND transaction_id IS NOT NULL AND address_id IS NULL)",
            name=op.f("ck_nodes_kind_shape"),
        ),
        sa.CheckConstraint(
            "direction IS NULL OR direction IN ('backward','forward')",
            name=op.f("ck_nodes_direction_values"),
        ),
        sa.CheckConstraint(
            "state IN ('frontier','expanded','terminal','excluded','pinned')",
            name=op.f("ck_nodes_state_values"),
        ),
        sa.ForeignKeyConstraint(["address_id"], ["addresses.id"], name=op.f("fk_nodes_address_id")),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
            name=op.f("fk_nodes_investigation_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"], ["transactions.id"], name=op.f("fk_nodes_transaction_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nodes")),
        sa.UniqueConstraint(
            "investigation_id",
            "kind",
            "address_id",
            "transaction_id",
            name="uq_nodes_identity",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index("ix_nodes_frontier", "nodes", ["investigation_id", "state"], unique=False)
    op.create_table(
        "edges",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("investigation_id", sa.UUID(), nullable=False),
        sa.Column("src_node_id", sa.BigInteger(), nullable=False),
        sa.Column("dst_node_id", sa.BigInteger(), nullable=False),
        sa.Column("movement_id", sa.BigInteger(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.CheckConstraint("kind IN ('movement','bridge')", name=op.f("ck_edges_kind_values")),
        sa.ForeignKeyConstraint(["dst_node_id"], ["nodes.id"], name=op.f("fk_edges_dst_node_id")),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
            name=op.f("fk_edges_investigation_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["movement_id"], ["movements.id"], name=op.f("fk_edges_movement_id")
        ),
        sa.ForeignKeyConstraint(["src_node_id"], ["nodes.id"], name=op.f("fk_edges_src_node_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_edges")),
        sa.UniqueConstraint(
            "investigation_id",
            "src_node_id",
            "dst_node_id",
            "movement_id",
            name="uq_edges_identity",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("finding_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("source_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heuristic", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Double(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('onchain_fact','heuristic_inference','third_party_claim')",
            name=op.f("ck_evidence_kind_values"),
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"], ["findings.id"], name=op.f("fk_evidence_finding_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("evidence")
    op.drop_table("edges")
    op.drop_index("ix_nodes_frontier", table_name="nodes")
    op.drop_table("nodes")
    op.drop_table("findings")
    op.drop_index("ix_movements_to_time", table_name="movements")
    op.drop_index("ix_movements_from_time", table_name="movements")
    op.drop_table("movements")
    op.drop_table("investigations")
    op.drop_table("transactions")
    op.drop_index("ix_provider_cache_chain_capability", table_name="provider_cache")
    op.drop_table("provider_cache")
    op.drop_table("assets")
    op.drop_table("addresses")
    # ### end Alembic commands ###
